# Generated by Django 4.1.3 on 2023-06-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('imei', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('rate_plants', models.CharField(max_length=10)),
                ('harvest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('humidity', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('soil_moisture', models.IntegerField()),
                ('brightness_of_lights', models.IntegerField()),
                ('heating', models.IntegerField()),
                ('ventilation', models.IntegerField()),
                ('window1', models.IntegerField()),
                ('window2', models.IntegerField()),
                ('pump1', models.IntegerField()),
                ('pump2', models.IntegerField()),
                ('error', models.IntegerField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.greenhouse')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reports')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('number_phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.greenhouse')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.users')),
            ],
        ),
    ]
